### ISSUE TITLE
actual deployment

### ISSUE THREAD

**Issue by robmcl4** [abstractionhq/gallery-gateway#139]

**Comment by chtinahow** [comment]
Set up meeting with Jay regarding deployment.
Talk about RIT auth
Mention what we need to install and if they have any questions about what we're doing
What can we do ourselves and how we would do it

**Comment by billdybas** [comment]
Also includes:
- verifying webpack build builds correctly
- prepping the app to use correct URLs and not localhost

**Comment by billdybas** [comment]
Also includes verifying what things we need to do to deploy the backend:
- https://expressjs.com/en/advanced/pm.html
- https://expressjs.com/en/advanced/best-practice-security.html
- https://expressjs.com/en/advanced/best-practice-performance.html
- https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html
- GraphQL specific deployment practices

**Comment by billdybas** [comment]
Do we need to run our Node API in a cluster: https://nodejs.org/api/cluster.html?
