### ISSUE TITLE
Add Contextual Error Messages for Students

### ISSUE THREAD

**Issue by billdybas** [abstractionhq/gallery-gateway#148]
- If there is an issue when submitting the entry forms, prevent the form from submitting, display an error, and don't clear the form (this is primarily for the Video Submission – letting the backend validate the URL is from YouTube or Vimeo)
~~(completed) If a student tries to upload a file that is too large, display an error that says what the maximum file size is~~

**Comment by billdybas** [comment]
Additionally, see #21

**Comment by kayladavis** [comment]
All contextual error messages mentioned in this issue have been added/surfaced in various PRs.
