### ISSUE TITLE
As an admin, I may want to exclude certain submissions from judging

### ISSUE THREAD

**Issue by billdybas** [abstractionhq/gallery-gateway#171]
We already have a property on entries on the backend for this.

We need to do the frontend for this:
- somewhere on the Admin interface for a show, they see a checkbox to exclude a submission from judging
- that entry does not appear in the judging order when a judge views the entries for a show
- if a judge tries to access an entry excluded from judging, they get a Not Found page

When should Admins be able to exclude something from judging? Before judging starts? If they exclude something that already has votes, should we remove the votes?

**Comment by kayladavis** [comment]
In the backend:  Add an "allowed for judging" param that allows to search for entries that are allowed to be shown.

**Comment by billdybas** [comment]
Frontend:

In the modal that appears when an Admin clicks on a row / submission in the "Submission" tab view, create a solid red button that says "Exclude From Judging". When clicked, it makes a mutation changing that property in the backend. The button then becomes white with a red outline and says "Include In Judging" which when clicked makes a mutation updating the status in the backend.
