### ISSUE TITLE
As a Judge I would like to see my progress on judging individual calls, so that I can see how much time I should set aside to finish judging.

### ISSUE THREAD

**Issue by robmcl4** [abstractionhq/gallery-gateway#26]
As a Judge I would like to see my progress on judging individual calls, so that I can see how much time I should set aside to finish judging.

**Comment by billdybas** [comment]
On the show cards on the Judge Dashboard, show a progress indicator (eg. 27 / 159)

Show a similar indicator on the top right of the Judging Interface so Judges know at a glance how much they have left to judge.

**Comment by chtinahow** [comment]
@billdybas The progress indicator should be on the top right according to the interface we came up with
![basic_voting_interface](https://user-images.githubusercontent.com/8568993/36273706-65527d30-1253-11e8-9378-15e10404f8c4.jpg)

**Comment by chtinahow** [comment]
This will just be the number out of how many completed

**Comment by billdybas** [comment]
We determined the most intuitive thing to put here was the index of the entry the Judge is looking at out of the total – gives context on how many are to the left and right.
