### ISSUE TITLE
As an administrator, I would like to see a report of all of the accepted pieces with the information associated with them so I would be able to reference back to this easily.

### ISSUE THREAD

**Issue by robmcl4** [abstractionhq/gallery-gateway#49]
As an administrator, I would like to see a report of all of the accepted pieces with the information associated with them so I would be able to reference back to this easily.

**Comment by chtinahow** [comment]
Bigger picture, artist name, dimensions

**Comment by kayladavis** [comment]
Report should have  name, group names, title, media type, size, email, and the answers to the questions. I think that is everything.
