### ISSUE TITLE
As an Administrator, I would like to download full-res images of submitted artwork files so that I can use them in other systems or for print / publication

### ISSUE THREAD

**Issue by robmcl4** [abstractionhq/gallery-gateway#52]
As an Administrator, I would like to download full-res images of submitted artwork files so that I can use them in other systems or for print / publication

**Comment by robmcl4** [comment]
As an Administrator, I would like downloaded submission files to follow a consistent naming scheme so that I know what student submitted it and what the title of the artwork is without having to look that information up elsewhere

**Comment by billdybas** [comment]
This task should be renamed to downloading _individual_ images from a show; rather than downloading an entire zip like in #54

**Comment by billdybas** [comment]
Should Judges be allowed to download images?

Yes -> Should we make a button underneath certain entries on the Judging Interface so Judges can download that photo / other media? Or should we just say, use right click -> save as?

No -> We should make a transparent overlay on photo/other submissions to prevent right click -> save as

**Comment by chtinahow** [comment]
I would say we just have a right click save as for MVP purposes although we can bring it up with Nannette if she sees it as a must have
